version: "3"
services:
  snapserver:
    image: jaedb/snapserver
    ports:
      - 1704:1704
      - 1705:1705
      - 1780:1780
    volumes:
      - /tmp/snapserver:/tmp
      - ./docker/snapserver/snapserver.conf:/etc/snapserver.conf
      - ./docker/snapserver/snapserver.json:/root/.config/snapserver/server.json
      - ./docker/snapserver/meta_mopidy.py:/usr/share/snapserver/plug-ins/meta_mopidy.py
  mopidy:
    image: jaedb/iris
    environment:
      - PIP_PACKAGES=Mopidy-YTMusic Mopidy-Tidal Mopidy-SoundCloud Mopidy-MusicBox-Webclient
    build:
      context: .
    depends_on:
      - snapserver
    ports:
      - 6600:6600
      - 6680:6680
    volumes:
      # - ./mopidy/iris:/iris/mopidy/iris # To use a locally-built UI 
      - ./docker/mopidy/iris:/var/lib/mopidy/iris # Iris-specific storage
      - ./docker/mopidy/m3u:/var/lib/mopidy/m3u # To persist local playlists
      - ./docker/mopidy/mopidy.conf:/config/mopidy.conf
      - /mnt/Music:/var/lib/mopidy/media
      - /tmp/snapserver:/tmp
